language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
    - cargo build --verbose --features serde
    - cargo test --verbose --features serde
    - |
        if [ $TRAVIS_RUST_VERSION == "nightly" ]; then
            rustup component add clippy-preview && cargo clippy -- -Dclippy::all
        fi
