language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
    - cargo build --verbose
    - cargo test --verbose
    - |
        if [ $TRAVIS_RUST_VERSION == "nightly" ]; then
            cargo install clippy && cargo clippy -- -Dclippy
        fi
